module.exports = {
	endOfLine: 'crlf',
	printWidth: 80,
	useTabs: true,
	tabWidth: 2,
	singleQuote: true,
	bracketSpacing: true,
	trailingComma: 'none',
	semi: true,
	importOrder: [
		'^react',
		'^next',
		'',
		'<THIRD_PARTY_MODULES>',
		'',
		'^@modules/common/hooks(.*)$',
		'',
		'^@styles/(.*)$',
		'^@utils/(.*)$',
		'',
		'^@public/(.*)$',
		'',
		'^[./]',
		'',
		'^@(.*)/(.*)/types(.*)$',
		'',
		'',
		'^@modules/(.*)/assets/(.*)$',
		''
	],
	importOrderBuiltinModulesToTop: true,
	importOrderCaseInsensitive: true,
	importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
	importOrderMergeDuplicateImports: true,
	importOrderCombineTypeAndValueImports: true,
	importOrderSeparation: false,
	importOrderSortSpecifiers: true
};
